name: NPM Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * 1'

jobs:
  npm-upgrade:
    name: NPM Upgrade
    runs-on: ubuntu-latest
    concurrency: upgrade
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run upgrade
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upgraded package dependencies [skip ci]
